### ISSUE TITLE
mergeMessagesWithPO fails for absolute paths

### ISSUE THREAD

**Issue by megapctr** [oliviertassinari/i18n-extract#19]
I've been using i18n-extract@0.2.0 so far. Today I upgraded to 0.4.1 and encountered a strange problem...

Here's how I use i18n-extract. I collect messages and update my translation files
```js
function collectMessages() {
    const jsFiles = path.join(__dirname, 'assets/js/**/*.js')
    const messages = i18nExtract.extractFromFiles(jsFiles, { marker: '__' })

    languages.forEach((lang) => {
        const out = translationFilePath(lang)
        <b>i18nExtract.mergeMessagesWithPO(messages, out, out)</b>
    })
}
```

`translationsFilePath` is a function that returns an _absolute path_. However, this absolute path gets then prepended with `/path/to/i18n-extract/lib/`.

This seems to be caused by `path.join(__dirname, ...)` in i18n-extract's code. See the `path.join` call on [this line](https://github.com/oliviertassinari/i18n-extract/blob/master/src/mergeMessagesWithPO.js#L6)

I think it's a flaw in the design of node's path.join, it seems to naively join everything it receives. Neverthe less, this probably should be fixed - maybe check if the path is relative or absolute first?

**Comment by oliviertassinari** [comment]
I'm no longer using the PO interface. Any idea how we could solve it?

**Comment by megapctr** [comment]
It's really simple, we could just wrap `path.join(...)` inside `if (path.isAbsolute(poFileName)`.

> I'm no longer using the PO interface

Have you found a good javascript i18n stack? Everything I could find was a complicated mess.

**Comment by oliviertassinari** [comment]
What about [`path.resolve`](https://nodejs.org/docs/latest/api/path.html) ?

> Have you found a good javascript i18n stack?

I'm using a simple key, value data structure on my side project.
Same at the office with the [rails i18n data structure](http://guides.rubyonrails.org/i18n.html).

**Comment by megapctr** [comment]
Right, `path.resolve` would be better.

**Comment by oliviertassinari** [comment]
> path.resolve would be better.

Does it work for you? 
Do you want to submit a PR? 2

**Comment by megapctr** [comment]
whoa, that was quick. I wanted to work on a PR tomorrow :) thanks for handling this
