### ISSUE TITLE
Get code fragments with keys

### ISSUE THREAD

**Issue by Phyks** [oliviertassinari/i18n-extract#31]
Hi,

It does not seem to be possible to get code fragments from which the keys were matched. I use `extractFromFiles` to extract i18n keys from my code and check whether all my translations are actually used and so on.

However, as I added it on a previous code base, I have a lot of jokers returned. Typically, when I pass a variable to my translator, I get a `*` joker in the output keys from `i18n-extract`.

I am trying to rewrite my code to narrow down these jokers, but it is quite painful to find where it comes from in the code. It would be a really great addition to return, besides the matched keys, the file where it is coming from and the code fragment which gave the match. I think all this info is already available to `i18n-extract`, so I may have missed something to get it from the library. :/

Thanks!

EDIT: This would be especially useful since `forbidDynamic` could give extra information on the code fragments to fix :)

**Comment by oliviertassinari** [comment]
@Phyks I agree, I love the idea!

**Comment by Phyks** [comment]
I might have a PR for this one as well, but I feel like I have to break the current API :/

My solution for now is to return

```
{
   key: [2, 3]
}
```

from `extractFromCode` running on

```
import i18n from 'i18n';
i18n('key');
i18n('key');
```

What do you think about it?

**Comment by oliviertassinari** [comment]
Why just not returning a rich object structure:
```js
[{
  key: 'mykey',
  loc: loc,
}]
```
