### ISSUE TITLE
Be able to ignore some lines of code through a comment

### ISSUE THREAD

**Issue by Phyks** [oliviertassinari/i18n-extract#32]
Hi,

It seems `i18n-extract` has the ability to include some translation strings through comments, with

```
/* i18n-extract key.comment */
```

However, I could not find a way to ignore a given line of code with a comment (similar to what `eslint` does). This could be useful as sometimes you really need a dynamic key but it can take a very limited range of values that you know in advance. You could ignore the dynamic key with a comment, and eventually add extra comments to include all the possible values.

This would really be awesome :)

Thanks!

**Comment by oliviertassinari** [comment]
I agree that would be a great addition to the library. I have been facing that issue quite some time in the past.

**Comment by Phyks** [comment]
I should have a PR fixing this soon.
