### ISSUE TITLE
Finding JSX React props

### ISSUE THREAD

**Issue by grydstedt** [oliviertassinari/i18n-extract#38]
Would be awesome to add support for Component values in react. `react-18next` for example you specify the key as a prop.

<I18N i18n={'someKey'} />

Would that be possible to support, I haven't dug into the code just yet.

**Comment by oliviertassinari** [comment]
I'm wondering, doesn't i18next already have some key extraction tools?

**Comment by grydstedt** [comment]
Ah, i'll look at that, thank you.
