### ISSUE TITLE
Unsupported node: ConditionalExpression & LogicalExpression

### ISSUE THREAD

**Issue by hjylewis** [oliviertassinari/i18n-extract#39]
There isn't support for instances of:
* `extractFromCode("i18n(cond && 'im conditional')")`
* `extractFromCode("i18n(cat ? 'cat' : 'not cat')")`

[getKey](https://github.com/oliviertassinari/i18n-extract/blob/master/src/extractFromCode.js#L6) should at least return `'*'`

**Comment by gsouf** [comment]
Hi @oliviertassinari can you, please, let us know if you plan to fix this issue?

**Comment by oliviertassinari** [comment]
@gsouf I don't.

**Comment by gsouf** [comment]
Ok, so it's maybe better just close the issue and let people know about your intention

**Comment by gsouf** [comment]
Just saw your edit, nevermind about the previous message then
