### ISSUE TITLE
support ES6

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/i18n-extract#4]
Would be great to support full ES6 feature.
I'm using facebook fork of esprima. This fork has an `Experimental support for ES6/Harmony (module, class, destructuring, ...)`. Don't know if it's enough.

**Comment by ariya** [comment]
Why don't just use the upstream Esprima 2.x? It gets enough support for ES6 features.

**Comment by oliviertassinari** [comment]
Because I want to support facebook jsx format (https://facebook.github.io/jsx/).

**Comment by brandonbloom** [comment]
This worked for my needs: https://github.com/brandonbloom/i18n-extract/commit/2d9871790def99b607b8e02965ea585d70bc813b

**Comment by oliviertassinari** [comment]
> This worked for my needs: brandonbloom@2d98717

Interesting, I'm gonna add an unit test with ES6 format. Will try to use `babel-core`.

**Comment by oliviertassinari** [comment]
Fixed with @6b01835740cb0523d03ce9d011a3e07b03d2938f.
