### ISSUE TITLE
`extractFromFiles` is not working with scopes

### ISSUE THREAD

**Issue by cyrilchampier** [oliviertassinari/i18n-extract#46]
if your file contains
```
i18n.t(patient.import_identifier ? 'with_import_identifier' : 'without_import_identifier',
      { scope: 'booking.patient.format.fullname.long' })
```
the 
`extractFromFiles` will returns:
```
[ { key: 'with_import_identifier',
    loc: SourceLocation { start: [Position], end: [Position],
    file: '.../PatientVerificationCard.js' },
  { key: 'without_import_identifier',
    loc: SourceLocation { start: [Position], end: [Position] },
    file:' .../PatientVerificationCard.js' } ]
```

**Comment by oliviertassinari** [comment]
What would you expect?

**Comment by cyrilchampier** [comment]
`'booking.patient.format.fullname.long.with_import_identifier'`
and
`'booking.patient.format.fullname.long.without_import_identifier'`

that would then pass the `findMissing` call

**Comment by oliviertassinari** [comment]
It's not Ruby on Rails. We have no scopes.

**Comment by cyrilchampier** [comment]
What do you mean by 'We' ?
If you are talking about `i18n-js`, yes there is:
in the doc, you can find it just before [this paragraph](https://github.com/fnando/i18n-js#number-formatting)

**Comment by oliviertassinari** [comment]
This package doesn't support any scopes feature. It's something I would personally avoid doing but I can understand the need. I'm happy to expose the needed hooks to make it work on your side.

**Comment by cyrilchampier** [comment]
I am not sure about what you call `hooks`.
I though this was a standard supported feature, if it's not, do not worry, we will just avoid them in our code for now :)

**Comment by rpellerin** [comment]
> I'm happy to expose the needed hooks to make it work on your side

That'd be great!

**Comment by oliviertassinari** [comment]
@rpellerin What I mean is that its a use case I think this library should allow people to use. I have closed the issue because I have no plan working on it nor I think its a priority. If you need to change something on the library to make it work, like a callback to transform the data, let me know. I would be happy to review your pull request.
