### ISSUE TITLE
Choose between flow or Typescript parser

### ISSUE THREAD

**Issue by mathieuletyrant** [oliviertassinari/i18n-extract#47]
The babylon parser loads the flow plugin by default: https://github.com/oliviertassinari/i18n-extract/blob/093abee3d3b1e0e11769441ed606baa86e64b391/src/extractFromCode.js#L51

We use typescript in our codebase so we got a error while running the script. Can we add an option to choose between flow or typescript?

**Comment by oliviertassinari** [comment]
@mathieuletyrant I believe Babel 7 now supports TypeScript. We can try to use the Flow plugin alongside the TypeScript plugging. If it doesn't work, I guess we need to provide an option to chose between the two.

**Comment by mathieuletyrant** [comment]
I tried to migrate to Babel 7 with `@babel/parser` instead of babylon with flow & typescript plugins and I got this error : 
<img width="529" alt="screen shot 2018-09-21 at 16 43 41" src="https://user-images.githubusercontent.com/2812991/45888101-8acd9e80-bdbd-11e8-99cd-07cd2328981e.png">

I think we must provide an option to choose between the two.

**Comment by oliviertassinari** [comment]
> I think we must provide an option to choose between the two.

@mathieuletyrant You are right, we can't https://github.com/babel/babel/blob/9d244ae66b6561b5d031bdb4e4eaacd043dcbbb7/packages/babel-parser/src/plugin-utils.js#L69, we need an option 👍.
