### ISSUE TITLE
Using extractFromFiles with Swig, Nunjucks or Twig templates

### ISSUE THREAD

**Issue by kokujin** [oliviertassinari/i18n-extract#53]
I am trying to extract keys using extractFromFiles with a templating engine with this module, a simple example of a template:

`<div>
    <div>{i18n('hello')}</div>
    <div>{{i18n('morning')}}</div>
</div>`

In all cases, double curly brackets, emits an error because it thinks the templates are JSX files
`/Research/i18n_extract_test/node_modules/babylon/lib/index.js:7333
          throw jsxError || err;`
the key is extracted from the translation with single curly braces no matter what the file endings are. How can I configure the module to recognise file types?
Thanks

**Comment by oliviertassinari** [comment]
We only support JavaScript files. You gonna need another tool for that.
