### ISSUE TITLE
expose `extractFromAST` API?

### ISSUE THREAD

**Issue by mxmul** [oliviertassinari/i18n-extract#54]
Hey – thanks for maintaining this project!

My team has built some tooling that runs a few Babel transforms on a source file before passing it to `i18n-extract`. Right now that means parsing the source file, applying our transformations on the AST, getting the transformed code, then passing to `extractFromCode`, which parses everything again. This double parsing can be pretty slow when applied to a large number of files, and I'd like some way to avoid it.

What do you think about exporting `extractFromAST` from this library? I can make a PR if you're okay with the approach

**Comment by oliviertassinari** [comment]
@mxmul Hi, your use case sounds good to me. Alternatively, we could try to support a custom Babel configuration.
https://github.com/oliviertassinari/i18n-extract/blob/7988b4fe414c5c98a929c86fd13cf172ea087683/src/extractFromCode.js#L50
