### ISSUE TITLE
Make distinction between keys with a star in the text and dynamic keys

### ISSUE THREAD

**Issue by gsouf** [oliviertassinari/i18n-extract#68]
Dynamic keys will be returned as a string with a star inside ti represent the unknown part. We cannot distinct them from string with a star inside. Can we make this more explicite, for example having a flag in the returned object saying that this is a dynamic string.

Or if it's too much work can we have an option to choose a custom token to replace the star character?

Whatever suits you, I'll open a PR

**Comment by gsouf** [comment]
@oliviertassinari please let me know so that I can prepare a PR

**Comment by oliviertassinari** [comment]
@gsouf I'm not maintaining the package anymore.
