### ISSUE TITLE
Support multiple arguments

### ISSUE THREAD

**Issue by megapctr** [oliviertassinari/i18n-extract#7]
Hello, I'd like to ask why doesn't this plugin allow multiple arguments in the translation function? I need this feature for i18next's interpolation feature:
```js
i18n("Hello, {{username}}!", {username: user.username});
```
To me, disallowing such messages seems pointless but maybe there is some rationale behind it?
I can submit a PR once we agree how to handle multiple arguments

**Comment by oliviertassinari** [comment]
> To me, disallowing such messages seems pointless but maybe there is some rationale behind it?

I have enforced this rule when migrating a code base to use `i18n`. As far as I remember, I was added to prevent a wrong usage of the API.
I'm fine with this request. But, let's ask @JeandeCampredon first.

**Comment by oliviertassinari** [comment]
I don't have any answer. Let's merge. Thanks! I will release with a minor, to be safer.

**Comment by oliviertassinari** [comment]
I have just released a `v0.2.0` with this change.

**Comment by megapctr** [comment]
awesome, thanks
